[package]
name = "common"
version = "0.1.0"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Common components for LNP/BP daemon suite"
keywords = ["bitcoin", "lightning", "cryptography"]
readme = "README.md"
edition = "2018"

[dependencies]
